### ISSUE TITLE
Add rest endpoint for get list all active keeprs

### ISSUE THREAD

**Issue by adaleorion** [JujaLabs/users#19]
For additional information about work with crm see her docs and ask @dtantsev

out: json array with active keeprs
```
[
 {
 uuid,
 description,
 from
 }
]
```

**Comment by OlgaKulikova** [comment]
@vitvyaz Необходимо доработать запрос. В таблице Keepers нет поля uuid, там есть поле contact_name_id, по которому можно сделать запрос в таблицу Contact и вытащить уже uuid. Затем склепать entity Keeper с нужными полями.
