### ISSUE TITLE
Fix Email/Gmail issue

### ISSUE THREAD

**Issue by dtantsev** [JujaLabs/users#4]
If user have only one email (gmail-compatible or not) - it stored in crm field "email", if user have both of them - email is stored in "email", gmail is stored in "c_gmail". Our service must return only gmail, that used in our services. Note that gmail addresses is not only like <xxx>@gmail.com, it can consist any domain.

**Comment by OlgaKulikova** [comment]
@dtantsev @danilkuznetsov Эта задача актуальна?

**Comment by adaleorion** [comment]
задача актуальна, я ее пофиксил,
сделал возврат поля gmail по умолчанию, а если его нет, тогда вернуть поле email
сделал в pr, когда фиксил ответ от crm
