### ISSUE TITLE
Fix response if user not found by slackName

### ISSUE THREAD

**Issue by NikolayNN** [JujaLabs/users#40]
Users microservice takes List of slackNames, and if one slackName not found return error with message "No users found by your request!".
But I want to know what slackName didn't find.

**Comment by OlgaKulikova** [comment]
Need to check and improve.

**Comment by VadimDyachenko** [comment]
@OlgaKulikova I checked this task. If slack name is not found, an exception will be thrown with text including this name. This one can be closed.
